### ISSUE TITLE
Update abapGit

### ISSUE THREAD

**Issue by mbtools** [hdegroot/zwordle#4]
Hi Hugo,

I looks to me like you are using a very old version of abapGit. On the current version 1.114, there are diffs related to the XML files (your's are missing the unicode BOM) and the program metadata (your's include STATE and VARCL, which was fixed in [2019](https://github.com/abapGit/abapGit/blob/7a9ba933374f65d6fe99e1e95b1c725d8813e90e/changelog.txt#L548) ). 

![image](https://user-images.githubusercontent.com/59966492/150772464-2202925e-0894-40c5-958f-775d6b19e8f1.png)

I highly recommend to use the latest version. 😃

**Comment by hdegroot** [comment]
Hi Marc, yes indeed. Reason I didn’t upgrade because I’ve only access to an old 7.31 system and I was afraid the newer version would not work on our old system. By any chance, do you know whether latest abapGit version works on 7.31? If so, I’ll use it to generate the repo.

**Comment by hdegroot** [comment]
BTW, kudos to Lars and team for making abapGit also available on old systems. I really appreciate that!

**Comment by hdegroot** [comment]
Done!  RTFM: abapGit requires SAP BASIS version 702 or higher :-)
Marc, thanks for pointing out this issue.

**Comment by mbtools** [comment]
Yeah, it's a bit of a hassle to keep it working with such old releases. Eventually, we will switch to 7.4 syntax and have everything downported automatically (thanks to Lars' abaplint).

**Comment by hdegroot** [comment]
Wish we could update ABAP language component without S4HANA, CDS, etc features. We are very interested in the pure language features like VALUE, DATA, literal operators, etc. Guess SAP wants us to upgrade. Curious which percentage of SAP installations is on 7.5 or higher.

iPhone. iTypos. iApologize.

________________________________
