### ISSUE TITLE
Word List

### ISSUE THREAD

**Issue by mbtools** [hdegroot/zwordle#5]
Not sure if there's a point of making improvements after god mode, but here's a better word list. Source: Collins Scrabble Words Dec 2021

[5-letter-words.txt](https://github.com/hdegroot/zwordle/files/7967610/5-letter-words.txt)

**Comment by hdegroot** [comment]
Marc, I will look into this. I'm aware current ZWORDLE dictionary has too many entries. (The current ZWORDLE dictionary contains a lot of "sound words", onomatopoeia, like PSTTT, etc. which the official Wordle does not use.)   FYI,  the Wordle JavaScript code contains in plain sight the dictionary of 5-letter words that Wordle deems as proper five-letter words. This dictionary has about 2300 entries, comparable to the list Collins Scrabble list you provided, and much less than the 5k+ entries ZWORDLE uses right now.

**Comment by mbtools** [comment]
things certainly change a lot when you take the config of the game into consideration (like its internal word and solution lists). 

i can imagine that the original author removes the solution list and shuffles it on the server side so you won't be able to use "god mode" (i would). 

therefore, it's best if the program works with as little assumptions as possible.

**Comment by hdegroot** [comment]
Marc, now ZWORDLE uses "Collins Scrabble Words Dec 2021" as the source for 5-letter words. Should be good! :-)
